/* ============================================================
 * 项目数据配置 —— 想加新项目？只需要：
 * 1. 在 project/ 下新建文件夹，放入 images/
 * 2. 在下面 PROJECTS 数组里加一段配置
 * featured: true  → 主线任务（自动成为一把魔王城钥匙）
 * accent          → 该项目档案页的主题色
 * media 每项: { src, label(标题), text(详细介绍), video/poster(视频) }
 * steam / paper   → 自动生成商店页 / 论文按钮
 * ============================================================ */

const PROJECTS = [
  {
    id: "project1",
    featured: true,
    title: "失心武士",
    subtitle: "LOST-HEART SAMURAI",
    type: "2D 像素动作冒险",
    accent: "#7ddb4f",
    tech: ["Unity", "C#"],
    tags: ["像素美术", "动作战斗", "Boss 战", "关卡设计"],
    thumb: "project/Project1/images/header.png",
    icon: "project/Project1/images/icon.png",
    short: "阴雨黑森林中的横版像素斩击冒险，完整的连招 · 技能 · 状态 · Boss AI 战斗系统。",
    desc: [
      "一款黑暗童话气质的横版像素动作游戏。你扮演一名迷失心智的武士，在落雨的巨木森林与幽暗地城之间穿行，斩杀蘑菇魔物，追寻自己丢失的『心』。",
      "游戏拥有一套完整的动作系统：多段连招、技能释放、状态效果（灼烧 / 中毒 / 眩晕）、敌人 AI 行为树，以及演出感十足的 Boss 战与剧情对话。",
    ],
    media: [
      { src: "project/Project1/images/header.png", label: "Boss 战 · 失心武士",
        text: "游戏的核心演出之一：雨夜森林中的 Boss 战。玩家的血条 / 蓝条 / 体力与 Boss 血条构成完整战斗 HUD，雨滴、光束与萤光全部由粒子与光照系统驱动，Boss 登场自带专属演出。" },
      { src: "project/Project1/images/story.png", label: "地城剧情演出",
        text: "地城篝火旁的剧情对话：神秘旅人指引前路。对话框、像素字体与场景光照都是自制——温暖的火光与幽暗的地城形成叙事上的呼吸感。" },
      { src: "project/Project1/images/1.png", label: "场景探索",
        text: "探索部分的场景设计：利用光照与雾效塑造纵深，场景里埋着机关、暗道与隐藏道具，奖励愿意到处乱走的玩家。" },
      { src: "project/Project1/images/samurai.mp4", poster: "project/Project1/images/samurai_poster.jpg", video: true, label: "武士连招演示",
        text: "多段连招实机：轻重攻击自由衔接，每一段都有独立的前摇、受击反馈与顿帧调校——手感是这个游戏打磨最久的部分。" },
      { src: "project/Project1/images/jineng.mp4", poster: "project/Project1/images/jineng_poster.jpg", video: true, label: "技能系统",
        text: "技能释放、冷却与资源消耗的完整循环，配合逐帧绘制的打击特效。技能可以打断连招衔接，形成自己的出招表。" },
      { src: "project/Project1/images/zhuangtai.mp4", poster: "project/Project1/images/zhuangtai_poster.jpg", video: true, label: "状态效果系统",
        text: "灼烧、中毒、眩晕等状态的叠加与结算：状态图标、粒子表现与伤害飘字三方联动，敌我通用同一套状态机。" },
      { src: "project/Project1/images/teki.mp4", poster: "project/Project1/images/teki_poster.jpg", video: true, label: "敌人 AI",
        text: "敌人 AI 行为树演示：索敌、追击、攻击、撤退之间的状态切换，不同敌人有不同的警戒范围与攻击欲望。" },
      { src: "project/Project1/images/gen.mp4", poster: "project/Project1/images/gen_poster.jpg", video: true, label: "实机流程",
        text: "一段完整的实机流程：从探索、遭遇战到演出的自然衔接，展示游戏的整体节奏。" },
    ],
  },
  {
    id: "steam_exit",
    featured: true,
    title: "第十层的逃生出口",
    subtitle: "FLOOR 10 EXIT",
    type: "3D 灵异异常逃脱 · 已上架 STEAM",
    accent: "#ff2d3d",
    steam: "https://store.steampowered.com/app/4148290/_/",
    tech: ["Unreal Engine", "蓝图 Blueprint"],
    tags: ["异常识别", "恐怖", "3D", "Steam 发行"],
    thumb: "project/steam_exit/images/header.jpg",
    icon: "project/steam_exit/images/header.jpg",
    short: "电梯不停把你带回『相同』的楼层——识破多达 31 处异常，抵达真正的 EXIT。",
    desc: [
      "你闯入了一栋曾经命案缠身的办公大楼。电梯不停把你带回看似『相同』的楼层，但每一层都可能藏着细微的异常——多达 31 处差异等你识破。",
      "判断正确才能继续上楼，看走眼就会坠回原点，还要躲开潜伏在楼层里的灵异危机。抵达最后的『EXIT』，找到真正的结局吧！已在 Steam 上架，欢迎加愿望单支持！",
    ],
    media: [
      { src: "project/steam_exit/images/shot1.jpg", label: "看似普通的办公楼层",
        text: "一切都从这个再普通不过的办公室开始。记住每一张桌椅、每一盆绿植的位置——下一次电梯门打开，它们可能就不一样了。" },
      { src: "project/steam_exit/images/shot2.jpg", label: "找出异常",
        text: "全游戏埋了多达 31 种异常：从家具位移、灯光变化，到根本不该存在的东西。观察力就是你的生存技能。" },
      { src: "project/steam_exit/images/shot3.jpg", label: "每一层都有点不对劲",
        text: "光照、贴图、声音都可能是线索——也可能是干扰项。UE 的动态光照让每一层的『不对劲』都藏得恰到好处。" },
      { src: "project/steam_exit/images/shot4.jpg", label: "……它就在那里",
        text: "红色房间。有些异常不满足于被你『找出来』——它们会主动来找你。撞见的时候，跑。" },
      { src: "project/steam_exit/images/shot5.jpg", label: "抵达 EXIT，还是坠回原点？",
        text: "判断正确上楼，判断失误坠回起点。穿过十层的试炼抵达『EXIT』，才能见到真正的结局。" },
    ],
  },
  {
    id: "steam_civ",
    featured: true,
    title: "数字文明：进化",
    subtitle: "DIGITAL CIVILIZATION",
    type: "文明模拟 / 策略 · 已上架 STEAM",
    accent: "#ffb300",
    steam: "https://store.steampowered.com/app/4620990/_/",
    tech: ["Vue", "JavaScript"],
    vibe: 90,
    tags: ["模拟", "策略", "文明进化", "Steam 发行"],
    thumb: "project/steam_civ/images/header.jpg",
    icon: "project/steam_civ/images/header.jpg",
    short: "从一撮原始人开始：管理资源、修建房屋、纵横外交，把文明一路进化成最强帝国。",
    desc: [
      "从原始文明起步：管理粮食、木材、石料，修建住房与工坊，让人口繁衍、科技萌芽，一步步把小部落养成无人能敌的伟大帝国。",
      "数值驱动的深度模拟：岗位分配、建造队列、科技树、随机事件与他国外交——每一个决策都在改写文明的走向。已在 Steam 上架！",
    ],
    media: [
      { src: "project/steam_civ/images/shot1.jpg", label: "建设 · 殖民地",
        text: "殖民地建设面板：住房、生产、军事建筑的建造队列与工期管理。劳动力是一切的基础——住房有余裕，人们才会组建家庭迎接新生命。" },
      { src: "project/steam_civ/images/shot3.jpg", label: "科技树 · 从原始到未来",
        text: "分层科技树贯穿整个文明史：每一项科技都实际改变生产、人口与社会参数，而不是单纯的数值解锁。研究方向决定你的文明长成什么样子。" },
      { src: "project/steam_civ/images/shot2.jpg", label: "资源与岗位管理",
        text: "资源仓库与岗位人口系统：粮食、木材、石料的产出链，猎人、伐木工、建筑工的就业分配——每一个岗位调整都牵动整条经济链。" },
      { src: "project/steam_civ/images/shot4.jpg", label: "事件日志 · 文明的故事",
        text: "事件日志记录文明的每一天：出生与死亡、建造与荣耀、拒绝过路的旅人、被野兽叼走的族人……数字背后自动生成你的文明叙事。" },
      { src: "project/steam_civ/images/shot5.jpg", label: "帝国的黎明",
        text: "当小部落成长为帝国，回头看事件日志，每一个数字背后都是你做过的决策。这是一个用 Vue 全栈实现的网页原生模拟游戏。" },
    ],
  },
  {
    id: "project2",
    featured: false,
    title: "魔女猫·登塔",
    subtitle: "WITCH CAT CLIMB",
    type: "休闲跳跃 · 竖屏",
    accent: "#57c8ff",
    tech: ["Unity", "C#"],
    tags: ["水彩 × 像素", "休闲", "魔法机制"],
    thumb: "project/Project2/images/header.png",
    icon: "project/Project2/images/ICON.png",
    short: "戴魔女帽的小黑猫沿着水彩城市高楼一路向上飞跃，用魔法刷新最大高度纪录。",
    desc: [
      "操控一只戴魔女帽的像素小黑猫，在水彩质感的欧风城市楼宇间不断向上跳跃攀升，躲避障碍、施放魔法，挑战自己的最高高度。",
      "美术上做了「水彩背景 × 像素角色」的混搭实验：柔软的城市色块与锐利的像素小猫形成强烈又可爱的反差。",
    ],
    media: [
      { src: "project/Project2/images/header.png", label: "云海之上",
        text: "越飞越高，风景随高度变化——冲出云海的那一刻是整个游戏的情绪高点。" },
      { src: "project/Project2/images/jieshao.png", label: "实机画面 · 登塔",
        text: "水彩质感的欧风楼宇 + 像素小黑猫：顶部记录当前高度与最高纪录，底部是魔法释放按钮。柔软与锐利的反差就是这个游戏的美术命题。" },
      { src: "project/Project2/images/level.png", label: "关卡设计",
        text: "关卡设计稿：平台节奏、道具分布与难度曲线——越往上，落点越苛刻，魔法越关键。" },
      { src: "project/Project2/images/player.mp4", poster: "project/Project2/images/player_poster.jpg", video: true, label: "玩家操作演示",
        text: "跳跃手感与魔法释放的实机演示：短按小跳、长按大跳，空中还有一次魔法救场的机会。" },
      { src: "project/Project2/images/npc.mp4", poster: "project/Project2/images/npc_poster.jpg", video: true, label: "NPC 互动",
        text: "沿途的 NPC 们：有的给你惊喜，有的纯粹捣乱——它们让每一次登塔都不太一样。" },
    ],
  },
  {
    id: "project3",
    featured: false,
    title: "Lux · AI 伙伴",
    subtitle: "LLM CHARACTER BOT",
    type: "AI / Discord Bot",
    accent: "#7ef0d4",
    tech: ["Python", "LLM", "Discord API"],
    paper: "https://arxiv.org/pdf/2504.13928",
    tags: ["LLM", "长期记忆", "AI 角色扮演", "论文"],
    thumb: "project/Project3/images/header.png",
    icon: "project/Project3/images/icon.png",
    short: "基于 LLM 的 AI 角色 Lux：拥有长期记忆的 Discord 伙伴，还能走进游戏里与你对话。",
    desc: [
      "Lux 是一个基于大语言模型打造的 AI 角色：她生活在 Discord 服务器里，记得每一位朋友说过的话——隔了很多天再来打招呼，她依然会认出你。",
      "同一个 Lux 也被接入了游戏内对话界面：在 Discord 里认识的她，可以在游戏世界中再次相遇。项目涵盖长期记忆管理、人格提示词工程与跨平台对话管线，相关研究已发表 arXiv 论文。",
    ],
    media: [
      { src: "project/Project3/images/header.png", label: "Discord × 游戏内对话",
        text: "同一个 Lux，两个世界：左边是游戏内的对话界面，右边是 Discord 聊天记录。跨平台共享同一份记忆与人格。" },
      { src: "project/Project3/images/llm.png", label: "长期记忆演示",
        text: "长期记忆实测：隔了一天再打招呼，Lux 依然记得你是谁、上次聊了什么——记忆检索与写入对用户完全透明。" },
      { src: "project/Project3/images/liuchengtu.png", label: "系统流程图",
        text: "系统管线：消息 → 记忆检索 → 人格提示词组装 → LLM 推理 → 双端输出。记忆库随对话持续沉淀，这部分工作整理成了 arXiv 论文。" },
      { src: "project/Project3/images/lux.png", label: "Lux 立绘",
        text: "Lux 的角色设定：蓝发、水手服，以及一点点害羞——「え、本当に会えているんですか…？」" },
    ],
  },
  {
    id: "art",
    featured: false,
    title: "绘画长廊",
    subtitle: "ART GALLERY",
    type: "插画 / 概念设计",
    accent: "#ff7a3c",
    tech: ["数位板", "厚涂"],
    tags: ["油画感", "场景概念", "角色"],
    thumb: "project/art/images/city.png",
    icon: "project/art/images/ICON.png",
    short: "从燃烧般的秋日湖泊到冰山与城堡——一批色彩奔放的数字绘画。",
    desc: [
      "数字绘画合集：秋日红叶淹没的湖上小舟、雾中城堡、极地冰山、都市黄昏……偏爱大胆的色块与厚涂笔触，让颜色自己讲故事。",
      "也包含角色与同人创作——魔女、勇者，以及一些奇怪但可爱的家伙。",
    ],
    media: [
      { src: "project/art/images/fengye.webp", label: "枫叶之湖",
        text: "把秋天整个烧起来的一张：橙红铺满画面，只留划船人一点冷色作为呼吸口。厚涂笔触 + 逆光树干的节奏感是这张的重点。" },
      { src: "project/art/images/chengbao.webp", label: "雾中城堡",
        text: "灰调空气透视练习：雾把城堡推远，再用几处高光把视线拉回来。" },
      { src: "project/art/images/bingshan.webp", label: "冰山",
        text: "冷色域的光影结构练习：冰的透光、海的沉色，蓝色内部找层次。" },
      { src: "project/art/images/city.png", label: "都市",
        text: "黄昏色温下的城市剪影，光从楼缝里漏出来的瞬间。" },
      { src: "project/art/images/daoqi.png", label: "刀气",
        text: "动势练习：用笔触方向和速度线表现一次挥砍的能量。" },
      { src: "project/art/images/huoyan.webp", label: "火焰研究",
        text: "火的形态拆解：从火舌的扭动到飞溅的火星，一张纯粹的元素练习。" },
      { src: "project/art/images/majyo.webp", label: "魔女",
        text: "角色设计：魔女与她的配色故事。" },
      { src: "project/art/images/yuusya.png", label: "勇者",
        text: "勇者角色练习——顺便成了这个网站世界观的起点。" },
      { src: "project/art/images/loser.png", label: "Loser",
        text: "一点小情绪的涂鸦，画完就好多了。" },
      { src: "project/art/images/Link.webp", label: "林克 · 同人",
        text: "海拉鲁的风：给最爱的游戏之一画的同人致敬。" },
    ],
  },
  {
    id: "blender",
    featured: false,
    title: "3D 工坊",
    subtitle: "BLENDER WORKSHOP",
    type: "3D 建模 / 渲染",
    accent: "#66b8ff",
    tech: ["Blender", "Cycles"],
    tags: ["Blender", "手办渲染", "场景"],
    thumb: "project/blender/images/header.png",
    icon: "project/blender/images/icon.png",
    short: "Blender 作品间：洛丽塔 Miku 手办、甜品静物、小木屋，以及会动的 VR 实验。",
    desc: [
      "用 Blender 搭建的小世界：从布料褶皱层层叠叠的洛丽塔 Miku 手办，到蛋糕、可乐这样的甜品静物渲染，再到木屋场景与流觞曲水的小景。",
      "也在尝试让它们动起来——转台展示动画与 VR 场景实验。",
    ],
    media: [
      { src: "project/blender/images/header.png", label: "Miku · 洛丽塔手办",
        text: "这套洛丽塔 Miku 是工坊的招牌：布料褶皱逐层建模，重点攻克裙撑结构与蕾丝边细节——给裙子多加三层褶的执念就是从这里来的。" },
      { src: "project/blender/images/BA.png", label: "BA 同人渲染",
        text: "蔚蓝档案同人：角色还原练习，重点在头发的分片建模与卡通渲染的描边控制。" },
      { src: "project/blender/images/dangao.png", label: "蛋糕静物",
        text: "甜品静物渲染：奶油的次表面散射、水果的高光——让人饿的材质研究。" },
      { src: "project/blender/images/kele.png", label: "可乐",
        text: "液体、玻璃与冰块的折射合奏，Cycles 焦散练习。" },
      { src: "project/blender/images/liushangqushui.png", label: "流觞曲水",
        text: "东方小景：曲水流杯的水面材质与庭园布景。" },
      { src: "project/blender/images/muwu.png", label: "木屋场景",
        text: "自然光照布光练习：晨光穿过木屋窗口的氛围。" },
      { src: "project/blender/images/wc.png", label: "小场景",
        text: "日常小场景练习——生活感来自细节堆叠。" },
      { src: "project/blender/images/miku.mp4", poster: "project/blender/images/miku_poster.jpg", video: true, label: "Miku 转台动画",
        text: "360° 转台展示：裙装的层次结构在旋转中一览无余。" },
      { src: "project/blender/images/VR.mp4", poster: "project/blender/images/VR_poster.jpg", video: true, label: "VR 场景实验",
        text: "把场景做成可进入的 VR 空间的实验——下一步是把手办们放进去。" },
    ],
  },
];
