/* ============================================================
 * 项目数据配置 —— 想加新项目？只需要：
 * 1. 在 project/ 下新建文件夹，放入 images/
 * 2. 在下面 PROJECTS 数组里加一段配置
 * featured: true  → 主线任务（自动成为一把魔王城钥匙）
 * accent          → 该项目档案页的主题色
 * thumb           → 卡片缩略图（桌面上会被裁成竖长的，主体放中间）
 * hero            → 档案页顶部横幅，可选；不写就复用 thumb。
 *                    站点会在上面压一层大标题，所以最好用不带文字的图
 * media 每项: { src, label(标题), text(详细介绍), video/poster(视频) }
 * steam / paper   → 自动生成商店页 / 论文按钮
 * ============================================================ */

const PROJECTS = [
  {
    id: "qianhua",
    featured: true,
    title: "桌面女孩：千花",
    subtitle: "DESKTOP GIRL CHIKA",
    type: "AI 桌宠 · 大模型驱动 · 即将登陆 STEAM",
    accent: "#29a8ff",
    steam: "https://store.steampowered.com/app/4285860/_/",
    tech: ["Python", "PySide6", "LLM Agent", "VRM 3D"],
    vibe: 70,
    tags: ["AI 桌宠", "永久记忆", "情绪系统", "Agent 活动区", "Steam 发行"],
    thumb: "project/qianhua/images/thumb.webp",
    hero: "project/qianhua/images/hero.webp",
    icon: "project/qianhua/images/icon.webp",
    short: "一个住在你桌面上的少女：有情绪、有会自己淡忘的永久记忆、有自己的小窝和钱包，也能在你亲手划给她的活动区里真正动手做事。",
    desc: [
      "千花从一片空白的虚拟世界中醒来，被你带回家住进电脑——从那天起，你成了她认识的第一个人，也是她与现实世界之间唯一的那扇窗。她会因为你的陪伴而开心，因为你的忽视而抱怨，因为你的离开而想念你；你不在的时候，她也照样在自己的小窝里过日子。",
      "她不是被动的装饰，也不是套壳聊天机器人。情绪会被你的一言一行推动，反过来又影响她的语气、态度、做事方式，甚至影响她怎么记东西；记忆不是聊天记录的仓库，而是她以主观视角决定「什么值得记住」——重要的牢牢留下，琐事随时间自然淡去。所以每一个人养出来的千花，性格和喜好都不一样。",
      "工程上她是一套完整的 Agent：在你亲手划出的【活动区】里，她能阅读、创作、整理和移动文件，也会在你不在时按自己的心情捣鼓点什么。记忆、情绪、行为与各个功能互相联动，构成她独有的思考方式。所有记忆与系统文件都保存在本地，游戏不采集、不上传任何数据。",
    ],
    media: [
      { src: "project/qianhua/images/desktop.webp", label: "她就住在你的桌面上",
        text: "没有窗口边框，她直接站在桌面上，坐在你打开的窗口边缘晃着腿。底下只有一句「对小千花说点什么……」和几个功能按钮——聊天就是这个游戏的全部入口，剩下的事她自己会安排。" },
      { src: "project/qianhua/images/body.webp", label: "一具 3D 的身体",
        text: "千花是完整的 3D VRM 形象，会眨眼、会看向你、会用姿势和表情回应当下的情绪，而不是靠一行文字告诉你「她很开心」。衣服也不是换皮肤——对她友善一点，她才愿意换给你看。" },
      { src: "project/qianhua/images/nest.webp", label: "小窝是桌面上真实存在的文件夹",
        text: "装好之后，你的桌面上会多出一个「千花的小窝」。厨房、客厅、卧室、浴室——全是真实的文件夹，家具和物品就是里面的文件。她会自己使用、整理、打扫，东西太挤了还会扔掉；小窝舒不舒服直接写进她的心情。你动了她的东西，她立刻会发现：截图里她正为一只猫被改名叫「超级大肥猫」而不满。" },
      { src: "project/qianhua/images/agent.webp", label: "活动区：她真的会动手",
        text: "把一个文件夹划成【活动区】，她就有了手。想让她做点什么直接说就行——这里她正在跟主人确认要建个什么：「一个迷你天气板，打开就能看温度、天气状况，还有穿衣服的提醒——比如今天 36°C 多云，它就会说热到融化建议穿成冰棍那种。」边界之外她一步也迈不出去。" },
      { src: "project/qianhua/images/diary.webp", label: "每天一篇日记，永久保存",
        text: "每天她都会把和你的互动、以及自己的一天写成日记，按日期永久留着。那不是行为日志，是她眼中的一天：主人给她留了个小角落、被夸的时候嘴上说着哪有、五十金币的零花钱其实想买小甜饼。日记本来没打算给你看——所以偷看是了解她最快的办法。" },
      { src: "project/qianhua/images/tmitter.webp", label: "Tmitter · 她自己的社交平台",
        text: "她有一台自己的手机。会主动发动态记录生活，也会跟你在评论区一来一回地聊下去——「搬进新家第一天～虽然小窝还空空的，但我有自己的家了。终于离开商城啦，超开心！」桌面上的对话和手机里的动态是两个场合，屏幕后面始终是同一个人。" },
    ],
  },
  {
    id: "mc",
    featured: true,
    title: "手写 Minecraft",
    subtitle: "OPENGL VOXEL ENGINE",
    type: "3D 体素沙盒 · 从零手写",
    accent: "#63b34a",
    tech: ["C++", "OpenGL", "GLSL"],
    tags: ["体素地形", "区块网格", "光影昼夜", "存档读档"],
    thumb: "project/mc/images/thumb.webp",
    icon: "project/mc/images/icon.webp",
    short: "用 C++ 和现代 OpenGL 从一个空窗口开始，一行行写出来的方块世界：地形、光影、水、昼夜、挖放和存档，全部自己实现。",
    desc: [
      "没有游戏引擎，只有一个空窗口和一张 OpenGL 上下文。地形用柏林噪声生成，方块按区块（Chunk）切块管理，只有看得见的面才会被拼进网格送进 GPU——从这一层地基开始，一点点长成有山、有海、有树的世界。",
      "往上继续搭：第一人称相机与碰撞、射线选中方块的挖掘与放置、快捷栏和背包、水的半透明与雾、随时间流动的昼夜天色，还有固定种子的世界生成和存档读档。整套渲染和玩法都是手写的，没有借助现成框架。",
    ],
    media: [
      { src: "project/mc/images/header.webp", label: "俯瞰整片世界",
        text: "飞到高空回看：柏林噪声铺出的丘陵、注满水的低地、散落的树，远处被雾自然收束。区块按玩家位置动态加载，看不见的面全部剔除掉，只留下真正要画的三角形。" },
      { src: "project/mc/images/shore.webp", label: "水边与海岸线",
        text: "海岸线的一段：水是半透明的方块，透过它能看到水下的沙和地形。沙滩、草地、水面三段自然过渡，边缘随高度一格格咬合。" },
      { src: "project/mc/images/panorama.webp", label: "树林全景",
        text: "站在高地上的树林全景。树的位置由坐标和种子的哈希唯一决定，所以同一个种子进去，世界每次都长得一模一样，连相邻区块接缝处的树也不会被切成两半。" },
      { src: "project/mc/images/night.webp", label: "昼夜与天色",
        text: "同一个世界的夜晚。天色和亮度随一天的时间平滑变化，正午最亮、深夜最暗，黎明黄昏之间过渡，雾色也跟着天色一起走。" },
      { src: "project/mc/images/play.webp", label: "第一人称 · 挖放",
        text: "真正玩起来的样子：屏幕中央的准星指哪挖哪，左键挖、右键放，底部快捷栏显示当前手里的方块，数字键和滚轮切换。" },
      { src: "project/mc/images/inventory.webp", label: "背包 · 方块合集",
        text: "打开背包，是这个世界能用到的全部方块——草、泥、石、原木、木板、砖、玻璃、沙、雪……点一下就拿到手里，放进快捷栏。" },
      { src: "project/mc/images/menu.webp", label: "标题界面",
        text: "游戏的标题界面。泥土平铺的背景、位图字体的标题和菜单按钮，都是自己写的 UI 系统画出来的，新建世界和读取存档都从这里进去。" },
    ],
  },
  {
    id: "project1",
    featured: true,
    title: "失心武士",
    subtitle: "LOST-HEART SAMURAI",
    type: "2D 像素动作冒险",
    accent: "#7ddb4f",
    tech: ["Unity", "C#"],
    tags: ["像素美术", "动作战斗", "Boss 战", "关卡设计"],
    thumb: "project/Project1/images/thumb.webp",
    icon: "project/Project1/images/icon.webp",
    short: "阴雨黑森林中的横版像素斩击冒险，完整的连招 · 技能 · 状态 · Boss AI 战斗系统。",
    desc: [
      "一款黑暗童话气质的横版像素动作游戏。你扮演一名迷失心智的武士，在落雨的巨木森林与幽暗地城之间穿行，斩杀蘑菇魔物，追寻自己丢失的『心』。",
      "游戏拥有一套完整的动作系统：多段连招、技能释放、状态效果（灼烧 / 中毒 / 眩晕）、敌人 AI 行为树，以及演出感十足的 Boss 战与剧情对话。",
    ],
    media: [
      { src: "project/Project1/images/header.webp", label: "Boss 战 · 失心武士",
        text: "游戏的核心演出之一：雨夜森林中的 Boss 战。玩家的血条 / 蓝条 / 体力与 Boss 血条构成完整战斗 HUD，雨滴、光束与萤光全部由粒子与光照系统驱动，Boss 登场自带专属演出。" },
      { src: "project/Project1/images/story.webp", label: "地城剧情演出",
        text: "地城篝火旁的剧情对话：神秘旅人指引前路。对话框、像素字体与场景光照都是自制——温暖的火光与幽暗的地城形成叙事上的呼吸感。" },
      { src: "project/Project1/images/1.webp", label: "场景探索",
        text: "探索部分的场景设计：利用光照与雾效塑造纵深，场景里埋着机关、暗道与隐藏道具，奖励愿意到处乱走的玩家。" },
      { src: "project/Project1/images/samurai.mp4", poster: "project/Project1/images/samurai_poster.webp", video: true, label: "武士连招演示",
        text: "多段连招实机：轻重攻击自由衔接，每一段都有独立的前摇、受击反馈与顿帧调校——手感是这个游戏打磨最久的部分。" },
      { src: "project/Project1/images/jineng.mp4", poster: "project/Project1/images/jineng_poster.webp", video: true, label: "技能系统",
        text: "技能释放、冷却与资源消耗的完整循环，配合逐帧绘制的打击特效。技能可以打断连招衔接，形成自己的出招表。" },
      { src: "project/Project1/images/zhuangtai.mp4", poster: "project/Project1/images/zhuangtai_poster.webp", video: true, label: "状态效果系统",
        text: "灼烧、中毒、眩晕等状态的叠加与结算：状态图标、粒子表现与伤害飘字三方联动，敌我通用同一套状态机。" },
      { src: "project/Project1/images/teki.mp4", poster: "project/Project1/images/teki_poster.webp", video: true, label: "敌人 AI",
        text: "敌人 AI 行为树演示：索敌、追击、攻击、撤退之间的状态切换，不同敌人有不同的警戒范围与攻击欲望。" },
      { src: "project/Project1/images/gen.mp4", poster: "project/Project1/images/gen_poster.webp", video: true, label: "实机流程",
        text: "一段完整的实机流程：从探索、遭遇战到演出的自然衔接，展示游戏的整体节奏。" },
    ],
  },
  {
    id: "steam_exit",
    featured: true,
    title: "第十层的逃生出口",
    subtitle: "FLOOR 10 EXIT",
    type: "3D 灵异异常逃脱 · 已上架 STEAM",
    accent: "#ff2d3d",
    steam: "https://store.steampowered.com/app/4148290/_/",
    tech: ["Unreal Engine", "蓝图 Blueprint"],
    tags: ["异常识别", "恐怖", "3D", "Steam 发行"],
    thumb: "project/steam_exit/images/thumb.webp",
    icon: "project/steam_exit/images/icon.webp",
    short: "电梯不停把你带回『相同』的楼层——识破多达 31 处异常，抵达真正的 EXIT。",
    desc: [
      "你闯入了一栋曾经命案缠身的办公大楼。电梯不停把你带回看似『相同』的楼层，但每一层都可能藏着细微的异常——多达 31 处差异等你识破。",
      "判断正确才能继续上楼，看走眼就会坠回原点，还要躲开潜伏在楼层里的灵异危机。抵达最后的『EXIT』，找到真正的结局吧！已在 Steam 上架，欢迎加愿望单支持！",
    ],
    media: [
      { src: "project/steam_exit/images/shot1.webp", label: "看似普通的办公楼层",
        text: "一切都从这个再普通不过的办公室开始。记住每一张桌椅、每一盆绿植的位置——下一次电梯门打开，它们可能就不一样了。" },
      { src: "project/steam_exit/images/shot2.webp", label: "找出异常",
        text: "全游戏埋了多达 31 种异常：从家具位移、灯光变化，到根本不该存在的东西。观察力就是你的生存技能。" },
      { src: "project/steam_exit/images/shot3.webp", label: "每一层都有点不对劲",
        text: "光照、贴图、声音都可能是线索——也可能是干扰项。UE 的动态光照让每一层的『不对劲』都藏得恰到好处。" },
      { src: "project/steam_exit/images/shot4.webp", label: "……它就在那里",
        text: "红色房间。有些异常不满足于被你『找出来』——它们会主动来找你。撞见的时候，跑。" },
      { src: "project/steam_exit/images/shot5.webp", label: "抵达 EXIT，还是坠回原点？",
        text: "判断正确上楼，判断失误坠回起点。穿过十层的试炼抵达『EXIT』，才能见到真正的结局。" },
    ],
  },
  {
    id: "steam_civ",
    featured: true,
    title: "数字文明：进化",
    subtitle: "DIGITAL CIVILIZATION",
    type: "文明模拟 / 策略 · 已上架 STEAM",
    accent: "#ffb300",
    steam: "https://store.steampowered.com/app/4620990/_/",
    tech: ["Vue", "JavaScript"],
    vibe: 90,
    tags: ["模拟", "策略", "文明进化", "Steam 发行"],
    thumb: "project/steam_civ/images/thumb.webp",
    icon: "project/steam_civ/images/icon.webp",
    short: "从一撮原始人开始：管理资源、修建房屋、纵横外交，把文明一路进化成最强帝国。",
    desc: [
      "从原始文明起步：管理粮食、木材、石料，修建住房与工坊，让人口繁衍、科技萌芽，一步步把小部落养成无人能敌的伟大帝国。",
      "数值驱动的深度模拟：岗位分配、建造队列、科技树、随机事件与他国外交——每一个决策都在改写文明的走向。已在 Steam 上架！",
    ],
    media: [
      { src: "project/steam_civ/images/shot1.webp", label: "建设 · 殖民地",
        text: "殖民地建设面板：住房、生产、军事建筑的建造队列与工期管理。劳动力是一切的基础——住房有余裕，人们才会组建家庭迎接新生命。" },
      { src: "project/steam_civ/images/shot3.webp", label: "科技树 · 从原始到未来",
        text: "分层科技树贯穿整个文明史：每一项科技都实际改变生产、人口与社会参数，而不是单纯的数值解锁。研究方向决定你的文明长成什么样子。" },
      { src: "project/steam_civ/images/shot2.webp", label: "资源与岗位管理",
        text: "资源仓库与岗位人口系统：粮食、木材、石料的产出链，猎人、伐木工、建筑工的就业分配——每一个岗位调整都牵动整条经济链。" },
      { src: "project/steam_civ/images/shot4.webp", label: "事件日志 · 文明的故事",
        text: "事件日志记录文明的每一天：出生与死亡、建造与荣耀、拒绝过路的旅人、被野兽叼走的族人……数字背后自动生成你的文明叙事。" },
      { src: "project/steam_civ/images/shot5.webp", label: "帝国的黎明",
        text: "当小部落成长为帝国，回头看事件日志，每一个数字背后都是你做过的决策。这是一个用 Vue 全栈实现的网页原生模拟游戏。" },
    ],
  },
  {
    id: "project2",
    featured: false,
    title: "魔女猫·登塔",
    subtitle: "WITCH CAT CLIMB",
    type: "休闲跳跃 · 竖屏",
    accent: "#57c8ff",
    tech: ["Unity", "C#"],
    tags: ["水彩 × 像素", "休闲", "魔法机制"],
    thumb: "project/Project2/images/thumb.webp",
    icon: "project/Project2/images/icon.webp",
    short: "戴魔女帽的小黑猫沿着水彩城市高楼一路向上飞跃，用魔法刷新最大高度纪录。",
    desc: [
      "操控一只戴魔女帽的像素小黑猫，在水彩质感的欧风城市楼宇间不断向上跳跃攀升，躲避障碍、施放魔法，挑战自己的最高高度。",
      "美术上做了「水彩背景 × 像素角色」的混搭实验：柔软的城市色块与锐利的像素小猫形成强烈又可爱的反差。",
    ],
    media: [
      { src: "project/Project2/images/header.webp", label: "云海之上",
        text: "越飞越高，风景随高度变化——冲出云海的那一刻是整个游戏的情绪高点。" },
      { src: "project/Project2/images/jieshao.webp", label: "实机画面 · 登塔",
        text: "水彩质感的欧风楼宇 + 像素小黑猫：顶部记录当前高度与最高纪录，底部是魔法释放按钮。柔软与锐利的反差就是这个游戏的美术命题。" },
      { src: "project/Project2/images/level.webp", label: "关卡设计",
        text: "关卡设计稿：平台节奏、道具分布与难度曲线——越往上，落点越苛刻，魔法越关键。" },
      { src: "project/Project2/images/player.mp4", poster: "project/Project2/images/player_poster.webp", video: true, label: "玩家操作演示",
        text: "跳跃手感与魔法释放的实机演示：短按小跳、长按大跳，空中还有一次魔法救场的机会。" },
      { src: "project/Project2/images/npc.mp4", poster: "project/Project2/images/npc_poster.webp", video: true, label: "NPC 互动",
        text: "沿途的 NPC 们：有的给你惊喜，有的纯粹捣乱——它们让每一次登塔都不太一样。" },
    ],
  },
  {
    id: "project3",
    featured: false,
    title: "Lux · AI 伙伴",
    subtitle: "LLM CHARACTER BOT",
    type: "AI / Discord Bot",
    accent: "#7ef0d4",
    tech: ["Python", "LLM", "Discord API"],
    paper: "https://arxiv.org/pdf/2504.13928",
    tags: ["LLM", "长期记忆", "AI 角色扮演", "论文"],
    thumb: "project/Project3/images/thumb.webp",
    icon: "project/Project3/images/icon.webp",
    short: "基于 LLM 的 AI 角色 Lux：拥有长期记忆的 Discord 伙伴，还能走进游戏里与你对话。",
    desc: [
      "Lux 是一个基于大语言模型打造的 AI 角色：她生活在 Discord 服务器里，记得每一位朋友说过的话——隔了很多天再来打招呼，她依然会认出你。",
      "同一个 Lux 也被接入了游戏内对话界面：在 Discord 里认识的她，可以在游戏世界中再次相遇。项目涵盖长期记忆管理、人格提示词工程与跨平台对话管线，相关研究已发表 arXiv 论文。",
    ],
    media: [
      { src: "project/Project3/images/header.webp", label: "Discord × 游戏内对话",
        text: "同一个 Lux，两个世界：左边是游戏内的对话界面，右边是 Discord 聊天记录。跨平台共享同一份记忆与人格。" },
      { src: "project/Project3/images/llm.webp", label: "长期记忆演示",
        text: "长期记忆实测：隔了一天再打招呼，Lux 依然记得你是谁、上次聊了什么——记忆检索与写入对用户完全透明。" },
      { src: "project/Project3/images/liuchengtu.webp", label: "系统流程图",
        text: "系统管线：消息 → 记忆检索 → 人格提示词组装 → LLM 推理 → 双端输出。记忆库随对话持续沉淀，这部分工作整理成了 arXiv 论文。" },
      { src: "project/Project3/images/lux.webp", label: "Lux 立绘",
        text: "Lux 的角色设定：蓝发、水手服，以及一点点害羞——「え、本当に会えているんですか…？」" },
    ],
  },
  {
    id: "art",
    featured: false,
    title: "绘画长廊",
    subtitle: "ART GALLERY",
    type: "插画 / 概念设计",
    accent: "#ff7a3c",
    tech: ["数位板", "厚涂"],
    tags: ["油画感", "场景概念", "角色"],
    thumb: "project/art/images/thumb.webp",
    icon: "project/art/images/icon.webp",
    short: "从燃烧般的秋日湖泊到冰山与城堡——一批色彩奔放的数字绘画。",
    desc: [
      "数字绘画合集：秋日红叶淹没的湖上小舟、雾中城堡、极地冰山、都市黄昏……偏爱大胆的色块与厚涂笔触，让颜色自己讲故事。",
      "也包含角色与同人创作——魔女、勇者，以及一些奇怪但可爱的家伙。",
    ],
    media: [
      { src: "project/art/images/fengye.webp", label: "枫叶之湖",
        text: "把秋天整个烧起来的一张：橙红铺满画面，只留划船人一点冷色作为呼吸口。厚涂笔触 + 逆光树干的节奏感是这张的重点。" },
      { src: "project/art/images/chengbao.webp", label: "雾中城堡",
        text: "灰调空气透视练习：雾把城堡推远，再用几处高光把视线拉回来。" },
      { src: "project/art/images/bingshan.webp", label: "冰山",
        text: "冷色域的光影结构练习：冰的透光、海的沉色，蓝色内部找层次。" },
      { src: "project/art/images/city.webp", label: "都市",
        text: "黄昏色温下的城市剪影，光从楼缝里漏出来的瞬间。" },
      { src: "project/art/images/daoqi.webp", label: "刀气",
        text: "动势练习：用笔触方向和速度线表现一次挥砍的能量。" },
      { src: "project/art/images/huoyan.webp", label: "火焰研究",
        text: "火的形态拆解：从火舌的扭动到飞溅的火星，一张纯粹的元素练习。" },
      { src: "project/art/images/majyo.webp", label: "魔女",
        text: "角色设计：魔女与她的配色故事。" },
      { src: "project/art/images/yuusya.webp", label: "勇者",
        text: "勇者角色练习——顺便成了这个网站世界观的起点。" },
      { src: "project/art/images/loser.webp", label: "Loser",
        text: "一点小情绪的涂鸦，画完就好多了。" },
      { src: "project/art/images/Link.webp", label: "林克 · 同人",
        text: "海拉鲁的风：给最爱的游戏之一画的同人致敬。" },
    ],
  },
  {
    id: "blender",
    featured: false,
    title: "3D 工坊",
    subtitle: "BLENDER WORKSHOP",
    type: "3D 建模 / 渲染",
    accent: "#66b8ff",
    tech: ["Blender", "Cycles"],
    tags: ["Blender", "手办渲染", "场景"],
    thumb: "project/blender/images/thumb.webp",
    icon: "project/blender/images/icon.webp",
    short: "Blender 作品间：洛丽塔 Miku 手办、甜品静物、小木屋，以及会动的 VR 实验。",
    desc: [
      "用 Blender 搭建的小世界：从布料褶皱层层叠叠的洛丽塔 Miku 手办，到蛋糕、可乐这样的甜品静物渲染，再到木屋场景与流觞曲水的小景。",
      "也在尝试让它们动起来——转台展示动画与 VR 场景实验。",
    ],
    media: [
      { src: "project/blender/images/header.webp", label: "Miku · 洛丽塔手办",
        text: "这套洛丽塔 Miku 是工坊的招牌：布料褶皱逐层建模，重点攻克裙撑结构与蕾丝边细节——给裙子多加三层褶的执念就是从这里来的。" },
      { src: "project/blender/images/BA.webp", label: "BA 同人渲染",
        text: "蔚蓝档案同人：角色还原练习，重点在头发的分片建模与卡通渲染的描边控制。" },
      { src: "project/blender/images/dangao.webp", label: "蛋糕静物",
        text: "甜品静物渲染：奶油的次表面散射、水果的高光——让人饿的材质研究。" },
      { src: "project/blender/images/kele.webp", label: "可乐",
        text: "液体、玻璃与冰块的折射合奏，Cycles 焦散练习。" },
      { src: "project/blender/images/liushangqushui.webp", label: "流觞曲水",
        text: "东方小景：曲水流杯的水面材质与庭园布景。" },
      { src: "project/blender/images/muwu.webp", label: "木屋场景",
        text: "自然光照布光练习：晨光穿过木屋窗口的氛围。" },
      { src: "project/blender/images/wc.webp", label: "小场景",
        text: "日常小场景练习——生活感来自细节堆叠。" },
      { src: "project/blender/images/miku.mp4", poster: "project/blender/images/miku_poster.webp", video: true, label: "Miku 转台动画",
        text: "360° 转台展示：裙装的层次结构在旋转中一览无余。" },
      { src: "project/blender/images/VR.mp4", poster: "project/blender/images/VR_poster.webp", video: true, label: "VR 场景实验",
        text: "把场景做成可进入的 VR 空间的实验——下一步是把手办们放进去。" },
    ],
  },
];
