/* ============================================================
 * 项目数据配置 —— 想加新项目？只需要：
 * 1. 在 project/ 下新建文件夹，放入 images/（至少一张 header.png）
 * 2. 在下面 PROJECTS 数组里加一段配置
 * featured: true  → 进入「主线任务」重点介绍区
 * featured: false → 进入「支线任务」普通区块
 * media 里 heavy: true 的条目（大 GIF）会显示「点击加载」按钮，
 * 不会拖慢首屏加载。
 * ============================================================ */

const PROJECTS = [
  {
    id: "project1",
    featured: true,
    title: "失心武士",
    subtitle: "LOST-HEART SAMURAI",
    type: "2D 像素动作冒险",
    tech: ["Unity", "C#"],
    tags: ["像素美术", "动作战斗", "Boss 战", "关卡设计"],
    thumb: "project/Project1/images/header.png",
    icon: "project/Project1/images/icon.png",
    short: "阴雨黑森林中的横版像素斩击冒险，完整的连招 · 技能 · 状态 · Boss AI 战斗系统。",
    desc: [
      "一款黑暗童话气质的横版像素动作游戏。你扮演一名迷失心智的武士，在落雨的巨木森林与幽暗地城之间穿行，斩杀蘑菇魔物，追寻自己丢失的『心』。",
      "游戏拥有一套完整的动作系统：多段连招、技能释放、状态效果（灼烧 / 中毒 / 眩晕）、敌人 AI 行为树，以及演出感十足的 Boss 战与剧情对话。",
    ],
    media: [
      { src: "project/Project1/images/header.png", label: "Boss 战 · 失心武士" },
      { src: "project/Project1/images/story.png", label: "地城剧情演出" },
      { src: "project/Project1/images/1.png", label: "场景探索" },
      { src: "project/Project1/images/samurai.mp4", poster: "project/Project1/images/samurai_poster.jpg", video: true, label: "武士连招演示" },
      { src: "project/Project1/images/jineng.mp4", poster: "project/Project1/images/jineng_poster.jpg", video: true, label: "技能系统" },
      { src: "project/Project1/images/zhuangtai.mp4", poster: "project/Project1/images/zhuangtai_poster.jpg", video: true, label: "状态效果系统" },
      { src: "project/Project1/images/teki.mp4", poster: "project/Project1/images/teki_poster.jpg", video: true, label: "敌人 AI" },
      { src: "project/Project1/images/gen.mp4", poster: "project/Project1/images/gen_poster.jpg", video: true, label: "实机演示" },
    ],
  },
  {
    id: "steam_exit",
    featured: true,
    title: "第十层的逃生出口",
    subtitle: "FLOOR 10 EXIT",
    type: "3D 灵异异常逃脱 · 已上架 STEAM",
    steam: "https://store.steampowered.com/app/4148290/_/",
    tech: ["Unreal Engine", "蓝图 Blueprint"],
    tags: ["异常识别", "恐怖", "3D", "Steam 发行"],
    thumb: "project/steam_exit/images/header.jpg",
    icon: "project/steam_exit/images/header.jpg",
    short: "电梯不停把你带回『相同』的楼层——识破多达 31 处异常，抵达真正的 EXIT。",
    desc: [
      "你闯入了一栋曾经命案缠身的办公大楼。电梯不停把你带回看似『相同』的楼层，但每一层都可能藏着细微的异常——多达 31 处差异等你识破。",
      "判断正确才能继续上楼，看走眼就会坠回原点，还要躲开潜伏在楼层里的灵异危机。抵达最后的『EXIT』，找到真正的结局吧！已在 Steam 上架，欢迎加愿望单支持！",
    ],
    media: [
      { src: "project/steam_exit/images/shot1.jpg", label: "看似普通的办公楼层" },
      { src: "project/steam_exit/images/shot2.jpg", label: "找出异常" },
      { src: "project/steam_exit/images/shot3.jpg", label: "每一层都有点不对劲" },
      { src: "project/steam_exit/images/shot4.jpg", label: "……它就在那里" },
      { src: "project/steam_exit/images/shot5.jpg", label: "抵达 EXIT，还是坠回原点？" },
    ],
  },
  {
    id: "steam_civ",
    featured: true,
    title: "数字文明：进化",
    subtitle: "DIGITAL CIVILIZATION",
    type: "文明模拟 / 策略 · 已上架 STEAM",
    steam: "https://store.steampowered.com/app/4620990/_/",
    tech: ["Vue", "JavaScript"],
    vibe: 90,
    tags: ["模拟", "策略", "文明进化", "Steam 发行"],
    thumb: "project/steam_civ/images/header.jpg",
    icon: "project/steam_civ/images/header.jpg",
    short: "从一撮原始人开始：管理资源、修建房屋、纵横外交，把文明一路进化成最强帝国。",
    desc: [
      "从原始文明起步：管理粮食、木材、石料，修建住房与工坊，让人口繁衍、科技萌芽，一步步把小部落养成无人能敌的伟大帝国。",
      "数值驱动的深度模拟：岗位分配、建造队列、科技树、随机事件与他国外交——每一个决策都在改写文明的走向。已在 Steam 上架！",
    ],
    media: [
      { src: "project/steam_civ/images/shot1.jpg", label: "建设 · 殖民地" },
      { src: "project/steam_civ/images/shot3.jpg", label: "科技树 · 从原始到未来" },
      { src: "project/steam_civ/images/shot2.jpg", label: "资源与岗位管理" },
      { src: "project/steam_civ/images/shot4.jpg", label: "事件日志 · 文明的故事" },
      { src: "project/steam_civ/images/shot5.jpg", label: "帝国的黎明" },
    ],
  },
  {
    id: "project2",
    featured: false,
    title: "魔女猫·登塔",
    subtitle: "WITCH CAT CLIMB",
    type: "休闲跳跃 · 竖屏",
    tech: ["Unity", "C#"],
    tags: ["水彩 × 像素", "休闲", "魔法机制"],
    thumb: "project/Project2/images/header.png",
    icon: "project/Project2/images/ICON.png",
    short: "戴魔女帽的小黑猫沿着水彩城市高楼一路向上飞跃，用魔法刷新最大高度纪录。",
    desc: [
      "操控一只戴魔女帽的像素小黑猫，在水彩质感的欧风城市楼宇间不断向上跳跃攀升，躲避障碍、施放魔法，挑战自己的最高高度。",
      "美术上做了「水彩背景 × 像素角色」的混搭实验：柔软的城市色块与锐利的像素小猫形成强烈又可爱的反差。",
    ],
    media: [
      { src: "project/Project2/images/header.png", label: "云海之上" },
      { src: "project/Project2/images/jieshao.png", label: "实机画面 · 登塔" },
      { src: "project/Project2/images/level.png", label: "关卡设计" },
      { src: "project/Project2/images/player.mp4", poster: "project/Project2/images/player_poster.jpg", video: true, label: "玩家操作演示" },
      { src: "project/Project2/images/npc.mp4", poster: "project/Project2/images/npc_poster.jpg", video: true, label: "NPC 互动" },
    ],
  },
  {
    id: "project3",
    featured: false,
    title: "Lux · AI 伙伴",
    subtitle: "LLM CHARACTER BOT",
    type: "AI / Discord Bot",
    tech: ["Python", "LLM", "Discord API"],
    paper: "https://arxiv.org/pdf/2504.13928",
    tags: ["LLM", "长期记忆", "AI 角色扮演", "论文"],
    thumb: "project/Project3/images/header.png",
    icon: "project/Project3/images/icon.png",
    short: "基于 LLM 的 AI 角色 Lux：拥有长期记忆的 Discord 伙伴，还能走进游戏里与你对话。",
    desc: [
      "Lux 是一个基于大语言模型打造的 AI 角色：她生活在 Discord 服务器里，记得每一位朋友说过的话——隔了很多天再来打招呼，她依然会认出你。",
      "同一个 Lux 也被接入了游戏内对话界面：在 Discord 里认识的她，可以在游戏世界中再次相遇。项目涵盖长期记忆管理、人格提示词工程与跨平台对话管线，相关研究已发表 arXiv 论文。",
    ],
    media: [
      { src: "project/Project3/images/header.png", label: "Discord × 游戏内对话" },
      { src: "project/Project3/images/llm.png", label: "长期记忆演示" },
      { src: "project/Project3/images/liuchengtu.png", label: "系统流程图" },
      { src: "project/Project3/images/lux.png", label: "Lux 立绘" },
    ],
  },
  {
    id: "art",
    featured: false,
    title: "绘画长廊",
    subtitle: "ART GALLERY",
    type: "插画 / 概念设计",
    tech: ["数位板", "厚涂"],
    tags: ["油画感", "场景概念", "角色"],
    thumb: "project/art/images/city.png",
    icon: "project/art/images/ICON.png",
    short: "从燃烧般的秋日湖泊到冰山与城堡——一批色彩奔放的数字绘画。",
    desc: [
      "数字绘画合集：秋日红叶淹没的湖上小舟、雾中城堡、极地冰山、都市黄昏……偏爱大胆的色块与厚涂笔触，让颜色自己讲故事。",
      "也包含角色与同人创作——魔女、勇者，以及一些奇怪但可爱的家伙。",
    ],
    media: [
      { src: "project/art/images/fengye.webp", label: "枫叶之湖" },
      { src: "project/art/images/chengbao.webp", label: "雾中城堡" },
      { src: "project/art/images/bingshan.webp", label: "冰山" },
      { src: "project/art/images/city.png", label: "都市" },
      { src: "project/art/images/daoqi.png", label: "刀气" },
      { src: "project/art/images/huoyan.webp", label: "火焰研究" },
      { src: "project/art/images/majyo.webp", label: "魔女" },
      { src: "project/art/images/yuusya.png", label: "勇者" },
      { src: "project/art/images/loser.png", label: "Loser" },
      { src: "project/art/images/Link.webp", label: "林克 · 同人" },
    ],
  },
  {
    id: "blender",
    featured: false,
    title: "3D 工坊",
    subtitle: "BLENDER WORKSHOP",
    type: "3D 建模 / 渲染",
    tech: ["Blender", "Cycles"],
    tags: ["Blender", "手办渲染", "场景"],
    thumb: "project/blender/images/header.png",
    icon: "project/blender/images/icon.png",
    short: "Blender 作品间：洛丽塔 Miku 手办、甜品静物、小木屋，以及会动的 VR 实验。",
    desc: [
      "用 Blender 搭建的小世界：从布料褶皱层层叠叠的洛丽塔 Miku 手办，到蛋糕、可乐这样的甜品静物渲染，再到木屋场景与流觞曲水的小景。",
      "也在尝试让它们动起来——转台展示动画与 VR 场景实验。",
    ],
    media: [
      { src: "project/blender/images/header.png", label: "Miku · 洛丽塔手办" },
      { src: "project/blender/images/BA.png", label: "BA 同人渲染" },
      { src: "project/blender/images/dangao.png", label: "蛋糕静物" },
      { src: "project/blender/images/kele.png", label: "可乐" },
      { src: "project/blender/images/liushangqushui.png", label: "流觞曲水" },
      { src: "project/blender/images/muwu.png", label: "木屋场景" },
      { src: "project/blender/images/wc.png", label: "小场景" },
      { src: "project/blender/images/miku.mp4", poster: "project/blender/images/miku_poster.jpg", video: true, label: "Miku 转台动画" },
      { src: "project/blender/images/VR.mp4", poster: "project/blender/images/VR_poster.jpg", video: true, label: "VR 场景实验" },
    ],
  },
];
